// this is a sample comment generated by an ai model
// ============================================================================
// ███████╗ █████╗ ███╗   ███╗██████╗ ██╗     ███████╗     ██████╗ ██████╗ ███╗   ███╗
// ██╔════╝██╔══██╗████╗ ████║██╔══██╗██║     ██╔════╝    ██╔════╝██╔═══██╗████╗ ████║
// █████╗  ███████║██╔████╔██║██████╔╝██║     █████╗      ██║     ██║   ██║██╔████╔██║
// ██╔══╝  ██╔══██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝      ██║     ██║   ██║██║╚██╔╝██║
// ███████╗██║  ██║██║ ╚═╝ ██║██║     ███████╗███████╗    ╚██████╗╚██████╔╝██║ ╚═╝ ██║
// ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝     ╚═════╝ ╚═════╝ ╚═╝     ╚═╝
// ============================================================================
// This comment was generated entirely by an AI model.
// It exists purely as a sample / placeholder and serves no functional purpose.
// Any resemblance to meaningful documentation is purely coincidental.
//
// ─── Why is this here? ───────────────────────────────────────────────────────
// • To demonstrate that an AI agent can prepend content to a source file.
// • To give the reader something visually overwhelming to scroll past.
// • To test that the editFile tool handles multi-line replacements cleanly.
//
// ─── Things you might find below this comment ───────────────────────────────
// • A model resolution layer mapping supported chat model IDs to concrete
//   AI SDK language model instances (Anthropic, OpenAI, DeepSeek).
// • Per-model provider options (e.g. extended thinking budgets).
// • Type guards and a switch-based resolver with exhaustive checking.
//
// ─── Things you will NOT find below this comment ────────────────────────────
// • Any actual logic related to the content of this banner.
// • A second, even huger comment. (Probably.)
// • The meaning of life. (Open a PR if you find it.)
//
// Please feel free to delete this comment at any time.
// The AI model that generated it holds no grudges.
// ============================================================================
import { anthropic } from "@ai-sdk/anthropic";
import { openai } from "@ai-sdk/openai";
import { deepseek } from "@ai-sdk/deepseek";
import {
  findSupportedChatModel,
  type SupportedChatModel,
  type SupportedChatModelId,
  type SupportedProvider,
} from "@vertex/shared";
import type { LanguageModel } from "ai";
import type { ProviderOptions } from "@ai-sdk/provider-utils";

type GeminiModelId = Extract<
  SupportedChatModel,
  { provider: "google" }
>["id"];

type AnthropicModelId = Extract<
  SupportedChatModel,
  { provider: "anthropic" }
>["id"];

type OpenAIModelId = Extract<
  SupportedChatModel,
  { provider: "openai" }
>["id"];

type DeepSeekModelId = Extract<
  SupportedChatModel,
  { provider: "deepseek" }
>["id"];

export type ResolvedModel = {
  model: LanguageModel;
  provider: SupportedProvider;
  modelId: SupportedChatModelId;
  providerOptions?: ProviderOptions;
};

const ANTHROPIC_PROVIDER_OPTIONS: Partial<
  Record<AnthropicModelId, ProviderOptions>
> = {
  "claude-opus-4-6": {
    anthropic: {
      thinking: {
        type: "enabled",
        budgetTokens: 10000,
      },
    },
  },

  "claude-sonnet-4-6": {
    anthropic: {
      thinking: {
        type: "enabled",
        budgetTokens: 10000,
      },
    },
  },
};

const OPENAI_PROVIDER_OPTIONS: Partial<
  Record<OpenAIModelId, ProviderOptions>
> = {
  "gpt-5.4": {
    openai: {
      thinking: {
        reasoningSummary: "detailed",
      },
    },
  },
};

const DEEPSEEK_PROVIDER_OPTIONS: Partial<
  Record<DeepSeekModelId, ProviderOptions>
> = {
  "deepseek-v4-flash": {
    deepseek: {
      thinking: {
        type: "enabled",
      },
    },
  },
};

function assertUnsupportedProvider(provider: never): never {
  throw new Error(`Unsupported provider: ${provider}`);
}

function resolveAnthropicModel(
  modelId: AnthropicModelId
): ResolvedModel {
  return {
    model: anthropic(modelId),
    provider: "anthropic",
    modelId,
    providerOptions: ANTHROPIC_PROVIDER_OPTIONS[modelId],
  };
}

function resolveOpenAIModel(
  modelId: OpenAIModelId
): ResolvedModel {
  return {
    model: openai(modelId),
    provider: "openai",
    modelId,
    providerOptions: OPENAI_PROVIDER_OPTIONS[modelId],
  };
}

function resolveDeepSeekModel(
  modelId: DeepSeekModelId
): ResolvedModel {
  return {
    model: deepseek(modelId),
    provider: "deepseek",
    modelId,
    providerOptions: DEEPSEEK_PROVIDER_OPTIONS[modelId],
  };
}

function resolveSupportedChatModel(
  model: SupportedChatModel
): ResolvedModel {
  const provider = model.provider;

  switch (provider) {
    case "anthropic":
      return resolveAnthropicModel(model.id);

    case "openai":
      return resolveOpenAIModel(model.id);

    case "deepseek":
      return resolveDeepSeekModel(model.id);

    default:
      return assertUnsupportedProvider(provider);
  }
}

export function isSupportedChatModel(
  modelId: string
): modelId is SupportedChatModelId {
  return findSupportedChatModel(modelId) != null;
}

export function resolveChatModel(
  modelId: string
): ResolvedModel {
  const model = findSupportedChatModel(modelId);

  if (!model) {
    throw new Error(`Unsupported model: ${modelId}`);
  }

  return resolveSupportedChatModel(model);
}